apiVersion: v1
kind: Service
metadata:
  name: streams-classifier
  labels:
    app: streams-classifier
spec:
  clusterIP: None
  selector:
    app: streams-classifier
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: streams-classifier
spec:
  serviceName: "streams-classifier"
  replicas: 1
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: streams-classifier
  template:
    metadata:
      labels:
        app: streams-classifier
    spec:
      containers:
        - name: kafka-streams-stockstat
          image: gcr.io/fresh-delight-322120/kafka-tweets:latest
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -DLOGLEVEL=INFO
          volumeMounts:
            - name: rocksdb
              mountPath: /var/lib/kafka-streams
  volumeClaimTemplates:
    - metadata:
        name: rocksdb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
